// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://daqohnsdkqtkukyfnntf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcW9obnNka3F0a3VreWZubnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MDA4MDcsImV4cCI6MjA0OTA3NjgwN30.6pkFMhiUM65kUxezSe32sYfcrgrJwQBmUpHmVf9Wvcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);